[package]
name = "bpfprof"
version = "0.1.0"
edition = "2024"

[build-dependencies]
libbpf-cargo = "0.24.4"

[dependencies]
libbpf-rs = "0.24.4"
libbpf-sys = "1.5.0"
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
